replicas: 2

backend:
  repository: ghcr.io/mmootz/backend
  tag: main
  pullPolicy: IfNotPresent

frontend:
  repository: ghcr.io/mmootz/frontend
  tag: main
  pullPolicy: IfNotPresent

redis_service:
  type: ClusterIP
  port: 6379 

frontend_service:
  type: LoadBalancer
  port: 80

backend_service:
  type: ClusterIP
  port: 5000

resources:
  limits:
     cpu: 200m
     memory: 256Mi


