- name: Deploy argocd
  kubernetes.core.helm:
    name: argocd
    chart_repo_url: https://argoproj.github.io/argo-helm
    chart_ref: argo-cd
    release_namespace: argocd
    kubeconfig: "{{ kubeconfig }}"
