apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend
  namespace: weather-app
  annotations:
    argocd.argoproj.io/tracking-id: weather-app:/Service:weather-app/backend
spec:
  ports:
  - name: backend
    port: {{ .Values.backend_service.port }}
    protocol: TCP
    targetPort: {{ .Values.backend_service.port }}
  selector:
    app: backend
  type: {{ .Values.backend_service.type }}
status:
  loadBalancer: {}
