apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: weather-app:/Service:weather-app/frontend
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
  namespace: weather-app
spec:
  ports:
  - name: frontend
    port: {{ .Values.frontend_service.port }}
    protocol: TCP
    targetPort: {{ .Values.frontend_service.port }}
  selector:
    app: frontend
  type: {{ .Values.frontend_service.type }}
status:
  loadBalancer: {}
