apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: weather-app:/Service:weather-app/redis
  creationTimestamp: null
  labels:
    app: redis
  name: redis
  namespace: weather-app
spec:
  ports:
  - name: redis
    port: {{ .Values.redis_service.port }}
    protocol: TCP
    targetPort: {{ .Values.redis_service.port }}
  selector:
    app: redis
  type: {{ .Values.redis_service.type }}
status:
  loadBalancer: {}
