- name: Deploy Metrics Server
  kubernetes.core.helm:
    name: metrics-server
    chart_repo_url: https://kubernetes-sigs.github.io/metrics-server/
    chart_ref: metrics-server
    release_namespace: kube-system
    kubeconfig: "{{ kubeconfig }}"
    values:
      args:
        - --kubelet-insecure-tls
